# SPDX_License_Identifier: GPL_2.0
dtb-$(CONFIG_MACH_LOONGSON64)	+= loongson3_4core_rs780e.dtb
dtb-$(CONFIG_MACH_LOONGSON64)	+= loongson3_8core_rs780e.dtb
dtb-$(CONFIG_MACH_LOONGSON64)	+= loongson3_4core_ls7a.dtb
dtb-$(CONFIG_MACH_LOONGSON64)	+= loongson3_r4_ls7a.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
